### ISSUE TITLE
Preset dropdown has white text on white background

### ISSUE THREAD

**Issue by ptrlrd** [pmndrs/market#28]
I wasn't able to quickly find it in the code base -- but if it isn't resolved by tomorrow I'll submit a PR. However, the preset menu color is the same as the background color. Images below. I would recommend color: #212224; or something similar to the menu color. 

Original:
![image](https://user-images.githubusercontent.com/37611278/118761376-26429600-b829-11eb-988d-2a4967890cd2.png)

Recommendation:
![image](https://user-images.githubusercontent.com/37611278/118761539-6bff5e80-b829-11eb-8bfa-091f45cdc384.png)

**Comment by SaraVieira** [comment]
Hey

That is an issue that comes from https://github.com/pmndrs/leva that's why you couldn't find it in the code.

**Comment by mattrossman** [comment]
I use leva in personal projects and don't have this issue. This is how it looks in the leva storybook:

![image](https://user-images.githubusercontent.com/22670878/126813715-8c1da3e4-7355-4675-a3c8-24eb1b7816a6.png)

I imagine there is something in the market implementation causing this?

**Comment by njm222** [comment]
seems to be resolved with #86

**Comment by mattrossman** [comment]
This issue is not resolved on my end, tested on that [preview deploy](https://market-pndhtwccs-pmndrs.vercel.app/model/zombie-car) as well as the [main URL](https://market.pmnd.rs/) in Firefox and Edge. Still white text on white background.

![image](https://user-images.githubusercontent.com/22670878/128791666-c07a5ed3-5af3-4554-9a45-e75160b52a15.png)

**Comment by njm222** [comment]
Ahhh my bad, I did not test those browsers.. thanks for the catch!

It might be tailwind messing with leva, I'll investigate it
