### ISSUE TITLE
Order by size

### ISSUE THREAD

**Issue by Angelk90** [pmndrs/market#64]
Hi @SaraVieira , 
It would be interesting to sort by ascending or descending size.

<img width="251" alt="Schermata 2021-06-11 alle 20 05 52" src="https://user-images.githubusercontent.com/20476002/121730798-717e5a80-caf0-11eb-98c6-8c884c124f0a.png">

**Comment by SaraVieira** [comment]
Added support to order by size here: https://github.com/pmndrs/market/commit/bc81eea6f7745cecefa41e1a1e3933459dd6a108

You can't toggle the direction but since that's not possible in any I made this issue:  https://github.com/pmndrs/market/issues/65 and will close this one since it's easier to track
