### ISSUE TITLE
Considering providing .glb download rather than .gltf

### ISSUE THREAD

**Issue by donmccurdy** [pmndrs/market#9]
Hi! Quick suggestion. Currently downloads use the .gltf extension with binary resources embedded as Data URIs. This adds 20-30% to the size of that binary data, and increases loader parsing time, compared to a binary .glb or to a .gltf with its binary resources in separate files. I'd recommend providing a `.glb` instead, or a ZIP containing `.gltf` and other files.

**Comment by SaraVieira** [comment]
Hey!

Glb files are really hard to handle in the browser and would require a complete overwrite if everything because they can't just be read that's why we went with gltf, with them we can parse them as json and literally just send people the json file 

We are doing some tests in small models like the ones we have and see if that 20/30% difference stands or if it's just big scenes because in terms of DX it is waaay better to use gltf

**Comment by donmccurdy** [comment]
Oh! Do you mean that the market page is doing some processing on the file in the web client? I guess I'd assumed these were static downloads from a CDN, sorry if I got that wrong. Or by DX do you mean easier for users to edit in an exported "Starter Project"?

I agree that for small files it doesn't matter much, but for the big ones (e.g. with heavy textures) the 20/30% adds up, and it stalls THREE.GLTFLoader for a bit while parsing the Data URI synchronously, unfortunately.

If you did want to convert `.gltf` to `.glb` in the client (e.g. when the user presses the download button) I'd be happy to help with that, it's not too complicated as conversions go.

**Comment by donmccurdy** [comment]
Anyway, I'll close this since it seems to be intentional, but still glad to help with that conversion if needed.
